version: '3'
services:
  blackbox:
    privileged: true
    environment:
      - DISPLAY=host.docker.internal:0.0
    build: .
    command: python src/sample.py
    volumes:
      - .:/src
    ports:
      - "3000:3000"
    expose:
      - "3000"