version: '3'
services:
  blackbox:
    privileged: true
    environment:
      - DISPLAY=host.docker.internal:0.0
    build: .
    command: ./src/startblackbox
    volumes:
      - .:/src
    ports:
      - "3000:3000"
  webserver:
    build: webserver
    volumes:
      - ./webserver:/src
    command: ./src/startwebserver
  setupgui:
    build: setupgui
    volumes:
      - ./setupgui:/setupgui
    command: /bin/bash
    ports:
      - "8080:8080"