version: '3'
services:
  blackbox:
    privileged: true
    environment:
      #- DISPLAY=host.docker.internal:0.0 - Windows
      DISPLAY: # - Linux
    build: .
    command: ./src/startblackbox
    volumes:
      - .:/src
      - $HOME/.Xauthority:/root/.Xauthority:rw # - Linux
    ports:
      - "3000:3000"
    network_mode: "host"
  webserver:
    build: webserver
    volumes:
      - ./webserver:/src
    command: ./src/startwebserver
  # webserver:
  #   image: vulnerables/web-dvwa
  # setupgui:
  #   build: setupgui
  #   volumes:
  #     - ./setupgui:/setupgui
  #   command: /bin/bash
  #   ports:
  #     - "8080:8080"
